Style
    Figure out better default font that supports bold and italic
    Different background for items
    Different background for Threats?
    Figure out white vs bone font coloring inconsistency
    Test and fix light mode
    GM rolls should be different style than player rolls
    Threats - Design change for ubermenschen?
character
    check if name field needs to be larger
    Make Injuries rollable
    Make Last Stand rollable
Macro
    PC roll without stats
    GM roll without Threat rating
Locations
    BUG: adding items is borked
chat messages
    clean them up
    use different dice for GM vs Player
    add more messaging about the roll
    Sort dice into categories
    add flashback re-rolling

Next Steps?
    create pre-made characters if RRD is okay with italic
    add map scene if RRD is okay with it
    add in BitD style clocks UI for Objectives?
    make dice clickable to allocate them on chat messages
    Make Injuries effect the sheet/rolls autmatically
