Styling
    Test and fix light mode
character
    check if name field needs to be larger

--------------- Wish list
Styling
    Different background for items
    Different background for Threats?
    Figure out white vs bone font coloring inconsistency
    Threats - Design change for ubermenschen?
    GM rolls should be different style than player rolls
Macros
    PC roll without stats
    GM roll without Threat rating
Chat messages
    use different dice for GM vs Player
    add more messaging about the roll
    Sort dice into categories
    make dice clickable to allocate them on chat messages
Rolls
    Make Injuries effect the sheet/rolls automatically
Pre-made
    create pre-made characters if RRD is okay with italic
    add map scene if RRD is okay with it
chat messages
    add flashback re-rolling